[package]
name = "ugly"
version = "0.1.0"
authors = ["Ashi Stanmore <me@ashikun.xyz>"]
edition = "2021"

[features]
# Enables the SDL backend.
backend_sdl = [ "sdl2" ]

[dependencies]
css-color-parser = "0.1.2"
ron = "0.7.1"
sdl2 = { version = "0.35.2", features = ["image"], optional = true }
serde = { version = "1.0.138", features = ["derive"] }
serde_with = "1.14.0"
thiserror = "1.0.31"

[dev-dependencies]
criterion = "0.3.5"

[[bench]]
name = "font_layout"
harness = false

[[bench]]
name = "text_write"
harness = false