# Small font

# Width and height of one character, less padding.
[char]
w = 5
h = 7

# Padding between characters (both on screen and in font bitmap).
[pad]
w = 1
h = 1

[width_overrides]
":" = 1
";" = 2
"(" = 3
")" = 3
"[" = 3
"]" = 3
"<" = 4
">" = 4
"I" = 1
"i" = 1
"j" = 2
"l" = 2
"t" = 4
"!" = 1
