# Medium font

# Width and height of one character, less padding.
[char]
w = 7
h = 9

# Padding between characters (both on screen and in font bitmap).
[pad]
w = 1
h = 1

[width_overrides]
"'" = 3
":" = 2
";" = 3
"(" = 4
")" = 4
"I" = 2
"f" = 5
"i" = 2
"j" = 3
"l" = 4
"t" = 5
